---------------------------------------------------------------------------------------------
--- ACTORES E: Especificación de los paquetes de actores
---------------------------------------------------------------------------------------------

-- ============================================================
-- PAQUETE: PK_ADMINISTRADOR
-- ============================================================
CREATE OR REPLACE PACKAGE PK_ADMINISTRADOR AS

    -- CATEGORIA
    PROCEDURE AD_CATEGORIA (xNOMBRE IN VARCHAR2, xDESCRIPCION IN VARCHAR2);
    PROCEDURE MOD_CATEGORIA (xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xDESCRIPCION IN VARCHAR2);
    PROCEDURE EL_CATEGORIA  (xID IN VARCHAR2);
    FUNCTION  CO_CATEGORIA  RETURN SYS_REFCURSOR;

    -- LIBRO
    PROCEDURE AD_LIBRO  (xTITULO IN VARCHAR2, xFECHA_PUBLICACION IN DATE, xIDIOMA IN VARCHAR2, xDESCRIPCION IN VARCHAR2, xID_CATEGORIA IN VARCHAR2);
    PROCEDURE MOD_LIBRO (xID IN VARCHAR2, xTITULO IN VARCHAR2, xFECHA_PUBLICACION IN DATE, xIDIOMA IN VARCHAR2, xDESCRIPCION IN VARCHAR2, xID_CATEGORIA IN VARCHAR2);
    PROCEDURE EL_LIBRO  (xID IN VARCHAR2);
    FUNCTION  CO_CATALOGO_LIBROS (xID_CATEGORIA IN VARCHAR2, xIDIOMA IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- AUTOR
    PROCEDURE AD_AUTOR  (xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xGENERO IN VARCHAR2, xNACIONALIDAD IN VARCHAR2);
    PROCEDURE MOD_AUTOR (xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xGENERO IN VARCHAR2, xNACIONALIDAD IN VARCHAR2);
    PROCEDURE EL_AUTOR  (xID IN VARCHAR2);
    FUNCTION  CO_AUTOR  (xNOMBRE IN VARCHAR2, xNACIONALIDAD IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- LIBRO_AUTOR
    PROCEDURE AD_AUTOR_LIBRO (xID_AUTOR IN VARCHAR2, xID_LIBRO IN VARCHAR2);
    PROCEDURE EL_AUTOR_LIBRO (xID_AUTOR IN VARCHAR2, xID_LIBRO IN VARCHAR2);

    -- EDITORIAL
    PROCEDURE AD_EDITORIAL  (xNOMBRE IN VARCHAR2, xCORREO IN VARCHAR2, xTELEFONO IN VARCHAR2, xPAIS IN VARCHAR2);
    PROCEDURE MOD_EDITORIAL (xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xCORREO IN VARCHAR2, xTELEFONO IN VARCHAR2, xPAIS IN VARCHAR2);
    PROCEDURE EL_EDITORIAL  (xID IN VARCHAR2);
    FUNCTION  CO_EDITORIAL  (xPAIS IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- EDICION
    PROCEDURE AD_EDICION  (xID_LIBRO IN VARCHAR2, xID_EDITORIAL IN VARCHAR2, xANIO IN DATE, xPAGINAS IN NUMBER);
    PROCEDURE MOD_EDICION (xID IN VARCHAR2, xID_LIBRO IN VARCHAR2, xID_EDITORIAL IN VARCHAR2, xANIO IN DATE, xPAGINAS IN NUMBER);
    PROCEDURE EL_EDICION  (xID IN VARCHAR2);
    FUNCTION  CO_EDICION  RETURN SYS_REFCURSOR;
    FUNCTION  CO_EDICION_LIBRO (xID_LIBRO IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- EJEMPLAR
    PROCEDURE AD_EJEMPLAR  (xID_EDICION IN VARCHAR2, xESTADO_FISICO IN VARCHAR2, xDISPONIBILIDAD IN BOOLEAN, xLOCALIZACION IN VARCHAR2, xFECHA_ADQ IN DATE);
    PROCEDURE MOD_EJEMPLAR (xID IN VARCHAR2, xESTADO_FISICO IN VARCHAR2, xDISPONIBILIDAD IN BOOLEAN, xLOCALIZACION IN VARCHAR2);
    PROCEDURE EL_EJEMPLAR  (xID IN VARCHAR2);
    FUNCTION  CO_EJEMPLAR  RETURN SYS_REFCURSOR;
    FUNCTION  CO_EJEMPLAR_EDICION (xID_EDICION IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- PROVEEDOR
    PROCEDURE AD_PROVEEDOR  (xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xCORREO IN VARCHAR2, xEMPRESA IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE MOD_PROVEEDOR (xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xCORREO IN VARCHAR2, xEMPRESA IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE EL_PROVEEDOR  (xID IN VARCHAR2);
    FUNCTION  CO_PROVEEDOR  RETURN SYS_REFCURSOR;

    -- COMPRA
    PROCEDURE AD_COMPRA  (xFECHA IN DATE, xTOTAL IN NUMBER, xESTADO IN VARCHAR2, xID_PROVEEDOR IN VARCHAR2);
    PROCEDURE MOD_COMPRA (xID IN VARCHAR2, xFECHA IN DATE, xTOTAL IN NUMBER, xESTADO IN VARCHAR2, xID_PROVEEDOR IN VARCHAR2);
    PROCEDURE EL_COMPRA  (xID IN VARCHAR2);
    FUNCTION  CO_COMPRA  RETURN SYS_REFCURSOR;
    FUNCTION  CO_PRODUCTOS_COMPRA (xID_COMPRA IN VARCHAR2) RETURN SYS_REFCURSOR;

    -- PRODUCTO_COMPRA
    PROCEDURE AD_PRODUCTO_COMPRA  (xID_COMPRA IN VARCHAR2, xID_LIBRO IN VARCHAR2, xCANTIDAD IN NUMBER, xPRECIO_UNIDAD IN NUMBER);
    PROCEDURE EL_PRODUCTO_COMPRA  (xID IN VARCHAR2);

    -- USUARIO / ADMINISTRADOR
    PROCEDURE AD_USUARIO       (xCORREO IN VARCHAR2, xROL IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE MOD_USUARIO      (xID IN VARCHAR2, xCORREO IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE EL_USUARIO       (xID IN VARCHAR2);
    PROCEDURE AD_ADMINISTRADOR (xID_USUARIO IN VARCHAR2, xPERMISOS IN VARCHAR2, xSEDE IN VARCHAR2);
    PROCEDURE MOD_ADMINISTRADOR(xID_USUARIO IN VARCHAR2, xPERMISOS IN VARCHAR2, xSEDE IN VARCHAR2);
    FUNCTION  CO_USUARIOS      RETURN SYS_REFCURSOR;
    FUNCTION  CO_ADMINISTRADORES RETURN SYS_REFCURSOR;

END PK_ADMINISTRADOR;
/
