---------------------------------------------------------------------------------------------
--- X SEGURIDAD: Limpieza de seguridad (solo rol Administrador, idempotente)
---------------------------------------------------------------------------------------------

-- ============================================================
-- 1. REVOCAR EXECUTE SOBRE PAQUETE ACTOR (si existe grant)
-- ============================================================
BEGIN
    EXECUTE IMMEDIATE 'REVOKE EXECUTE ON PK_ADMINISTRADOR FROM ROL_ADMINISTRADOR';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignorar si el rol o el grant no existen
        IF SQLCODE NOT IN (-1919, -1924, -4043, -1031) THEN
            RAISE;
        END IF;
END;
/

-- ============================================================
-- 2. REVOCAR PERMISOS SOBRE TABLAS (si existen grants)
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Usuario         FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Administrador   FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Categoria       FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Libro           FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Libro_Autor     FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Autor           FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Editorial       FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Edicion         FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Ejemplar        FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Proveedor       FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Compra          FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT, UPDATE, DELETE ON Producto_Compra FROM ROL_ADMINISTRADOR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1919, -1924, -942, -1031) THEN RAISE; END IF; END;
/

-- ============================================================
-- 3. ELIMINAR PAQUETE DE ACTOR (si existe)
-- ============================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE PK_ADMINISTRADOR';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-4043, -1031) THEN
            RAISE;
        END IF;
END;
/

-- ============================================================
-- 4. ELIMINAR ROL (si existe)
-- ============================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROL_ADMINISTRADOR';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1919, -1924, -1031) THEN
            RAISE;
        END IF;
END;
/
