-- ============================================================
--  BOOKTRACK -- CICLO 2
--  Componentes: Especificacion, Implementacion, Eliminacion
--  y Casos de Prueba de Paquetes
-- ============================================================
-- ============================================================
-- CRUDE - ESPECIFICACION DE LOS PAQUETES
-- ============================================================

CREATE OR REPLACE PACKAGE PC_PRESTAMO IS
    PROCEDURE AD_PRESTAMO(xID_CLIENTE IN VARCHAR2, xID_EJEMPLAR IN VARCHAR2, xFECHA_PRESTAMO IN DATE);
    PROCEDURE MOD_PRESTAMO(xID IN VARCHAR2, xFECHA_PRESTAMO IN DATE);
    PROCEDURE ELI_PRESTAMO(xID IN VARCHAR2, xID_ADMIN IN VARCHAR2);
    FUNCTION  CO_PRESTAMO(xFECHA_PRESTAMO IN DATE) RETURN SYS_REFCURSOR;
END PC_PRESTAMO;
/

CREATE OR REPLACE PACKAGE PC_DEVOLUCION IS
    PROCEDURE AD_DEVOLUCION(xID_PRESTAMO IN VARCHAR2, xESTADO_ENTREGA IN BOOLEAN, xOBSERVACIONES IN VARCHAR2);
    PROCEDURE MOD_DEVOLUCION(xID IN VARCHAR2, xOBSERVACIONES IN VARCHAR2);
    PROCEDURE ELI_DEVOLUCION(xID IN VARCHAR2);
    FUNCTION  CO_DEVOLUCION(xESTADO_ENTREGA IN BOOLEAN) RETURN SYS_REFCURSOR;
END PC_DEVOLUCION;
/

CREATE OR REPLACE PACKAGE PC_MULTA IS
    PROCEDURE AD_MULTA(xID_DEVOLUCION IN VARCHAR2, xMOTIVO IN VARCHAR2, xMONTO_ACUMULADO IN NUMBER);
    PROCEDURE MOD_MULTA(xID IN VARCHAR2, xMONTO_ACUMULADO IN NUMBER, xESTADO IN VARCHAR2);
    PROCEDURE ELI_MULTA(xID IN VARCHAR2, xID_ADMIN IN VARCHAR2);
    FUNCTION  CO_MULTA(xESTADO IN VARCHAR2) RETURN SYS_REFCURSOR;
END PC_MULTA;
/

CREATE OR REPLACE PACKAGE PC_PAGO IS
    PROCEDURE AD_PAGO(xID_MULTA IN VARCHAR2, xMONTO_ABONADO IN NUMBER, xMETODO_PAGO IN VARCHAR2);
    PROCEDURE MOD_PAGO(xID IN VARCHAR2, xMETODO_PAGO IN VARCHAR2);
    PROCEDURE ELI_PAGO(xID IN VARCHAR2);
    FUNCTION  CO_PAGO(xESTADO IN VARCHAR2) RETURN SYS_REFCURSOR;
END PC_PAGO;
/

-- ============================================================
--  BOOKTRACK -- SECUENCIAS CICLO 2
--  Crear ANTES de compilar los Package Bodies
-- ============================================================
CREATE SEQUENCE SQ_PRESTAMO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_DEVOLUCION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_MULTA      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_PAGO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;