-- ============================================================
--  BOOKTRACK -- CICLO 1
--  Componentes: Especificacion, Implementacion, Eliminacion
--  y Casos de Prueba de Paquetes
-- ===========================================================
-- ============================================================
-- CRUDE - ESPECIFICACION DE LOS PAQUETES
-- ============================================================
CREATE OR REPLACE PACKAGE PC_CATEGORIA IS
    PROCEDURE AD_CATEGORIA(xNOMBRE IN VARCHAR2, xDESCRIPCION IN VARCHAR2);
    PROCEDURE MOD_CATEGORIA(xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xDESCRIPCION IN VARCHAR2);
    PROCEDURE ELI_CATEGORIA(xID IN VARCHAR2);
    FUNCTION  CO_CATEGORIA RETURN SYS_REFCURSOR;
END PC_CATEGORIA;
/

CREATE OR REPLACE PACKAGE PC_AUTOR IS
    PROCEDURE AD_AUTOR(xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xGENERO IN VARCHAR2, xNACIONALIDAD IN VARCHAR2);
    PROCEDURE MOD_AUTOR(xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xGENERO IN VARCHAR2, xNACIONALIDAD IN VARCHAR2);
    PROCEDURE ELI_AUTOR(xID IN VARCHAR2);
    FUNCTION  CO_AUTOR RETURN SYS_REFCURSOR;
END PC_AUTOR;
/

CREATE OR REPLACE PACKAGE PC_EDITORIAL IS
    PROCEDURE AD_EDITORIAL(xNOMBRE IN VARCHAR2, xCORREO IN VARCHAR2, xTELEFONO IN VARCHAR2, xPAIS IN VARCHAR2);
    PROCEDURE MOD_EDITORIAL(xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xCORREO IN VARCHAR2, xTELEFONO IN VARCHAR2, xPAIS IN VARCHAR2);
    PROCEDURE ELI_EDITORIAL(xID IN VARCHAR2);
    FUNCTION  CO_EDITORIAL RETURN SYS_REFCURSOR;
END PC_EDITORIAL;
/

CREATE OR REPLACE PACKAGE PC_LIBRO IS
    PROCEDURE AD_LIBRO(xIDCATEGORIA IN VARCHAR2, xTITULO IN VARCHAR2, xDESCRIPCION IN VARCHAR2, xFECHA_PUBLICACION IN DATE, xIDIOMA IN VARCHAR2);
    PROCEDURE MOD_LIBRO(xID IN VARCHAR2, xIDCATEGORIA IN VARCHAR2, xTITULO IN VARCHAR2, xDESCRIPCION IN VARCHAR2, xIDIOMA IN VARCHAR2);
    PROCEDURE ELI_LIBRO(xID IN VARCHAR2);
    PROCEDURE AD_LIBRO_AUTOR(xIDLIBRO IN VARCHAR2, xIDAUTOR IN VARCHAR2);
    PROCEDURE ELI_LIBRO_AUTOR(xIDLIBRO IN VARCHAR2, xIDAUTOR IN VARCHAR2);
    FUNCTION  CO_LIBRO RETURN SYS_REFCURSOR;
    FUNCTION  CO_LIBRO_CAT(xIDCATEGORIA IN VARCHAR2) RETURN SYS_REFCURSOR;
END PC_LIBRO;
/

CREATE OR REPLACE PACKAGE PC_EDICION IS
    PROCEDURE AD_EDICION(xIDLIBRO IN VARCHAR2, xIDEDITORIAL IN VARCHAR2, xANIO IN DATE, xPAGINAS IN NUMBER);
    PROCEDURE MOD_EDICION(xID IN VARCHAR2, xIDLIBRO IN VARCHAR2, xIDEDITORIAL IN VARCHAR2, xANIO IN DATE, xPAGINAS IN NUMBER);
    PROCEDURE ELI_EDICION(xID IN VARCHAR2);
    FUNCTION  CO_EDICION RETURN SYS_REFCURSOR;
    FUNCTION  CO_EDICION_LIBRO(xIDLIBRO IN VARCHAR2) RETURN SYS_REFCURSOR;
END PC_EDICION;
/

CREATE OR REPLACE PACKAGE PC_EJEMPLAR IS
    PROCEDURE AD_EJEMPLAR(xIDEDICION IN VARCHAR2, xESTADOFISICO IN VARCHAR2, xDISPONIBILIDAD IN CHAR, xLOCALIZACION IN VARCHAR2, xFECHAADQUISICION IN DATE);
    PROCEDURE MOD_EJEMPLAR(xID IN VARCHAR2, xESTADOFISICO IN VARCHAR2, xDISPONIBILIDAD IN CHAR, xLOCALIZACION IN VARCHAR2);
    PROCEDURE ELI_EJEMPLAR(xID IN VARCHAR2);
    FUNCTION  CO_EJEMPLAR RETURN SYS_REFCURSOR;
    FUNCTION  CO_EJEMPLAR_EDICION(xIDEDICION IN VARCHAR2) RETURN SYS_REFCURSOR;
END PC_EJEMPLAR;
/

CREATE OR REPLACE PACKAGE PC_PROVEEDOR IS
    PROCEDURE AD_PROVEEDOR(xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xCORREO IN VARCHAR2, xEMPRESA IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE MOD_PROVEEDOR(xID IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xCORREO IN VARCHAR2, xEMPRESA IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE ELI_PROVEEDOR(xID IN VARCHAR2);
    FUNCTION  CO_PROVEEDOR RETURN SYS_REFCURSOR;
END PC_PROVEEDOR;
/

CREATE OR REPLACE PACKAGE PC_COMPRA IS
    PROCEDURE AD_COMPRA(xIDPROVEEDOR IN VARCHAR2, xFECHA IN DATE, xTOTAL IN NUMBER, xESTADO IN VARCHAR2);
    PROCEDURE MOD_COMPRA(xID IN VARCHAR2, xFECHA IN DATE, xTOTAL IN NUMBER, xESTADO IN VARCHAR2);
    PROCEDURE ELI_COMPRA(xID IN VARCHAR2);
    PROCEDURE AD_PRODUCTO_COMPRA(xIDCOMPRA IN VARCHAR2, xIDLIBRO IN VARCHAR2, xCANTIDAD IN NUMBER, xPRECIOUNIDAD IN NUMBER);
    PROCEDURE ELI_PRODUCTO_COMPRA(xID IN VARCHAR2);
    FUNCTION  CO_COMPRA RETURN SYS_REFCURSOR;
    FUNCTION  CO_PRODUCTOS_COMPRA(xIDCOMPRA IN VARCHAR2) RETURN SYS_REFCURSOR;
END PC_COMPRA;
/

CREATE OR REPLACE PACKAGE PC_USUARIO IS
    PROCEDURE AD_USUARIO(xCORREO IN VARCHAR2, xROL IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE MOD_USUARIO(xID IN VARCHAR2, xCORREO IN VARCHAR2, xNOMBRE IN VARCHAR2, xAPELLIDOS IN VARCHAR2, xTELEFONO IN VARCHAR2);
    PROCEDURE ELI_USUARIO(xID IN VARCHAR2);
    PROCEDURE AD_ADMINISTRADOR(xIDUSUARIO IN VARCHAR2, xPERMISOS IN VARCHAR2, xSEDE IN VARCHAR2);
    PROCEDURE MOD_ADMINISTRADOR(xIDUSUARIO IN VARCHAR2, xPERMISOS IN VARCHAR2, xSEDE IN VARCHAR2);
    PROCEDURE ELI_ADMINISTRADOR(xIDUSUARIO IN VARCHAR2);
    FUNCTION  CO_USUARIOS RETURN SYS_REFCURSOR;
    FUNCTION  CO_USUARIO_ROL(xROL IN VARCHAR2) RETURN SYS_REFCURSOR;
    FUNCTION  CO_ADMINISTRADORES RETURN SYS_REFCURSOR;
END PC_USUARIO;
/

-- ============================================================
--  BOOKTRACK -- SECUENCIAS
--  Crear ANTES de compilar los Package Bodies
-- ============================================================

CREATE SEQUENCE SQ_CATEGORIA  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_AUTOR      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_EDITORIAL  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_LIBRO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_EDICION    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_EJEMPLAR   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_PROVEEDOR  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_COMPRA     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_PROD_COMP  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_USUARIO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;