
-- ============================================================
-- XCRUD - ELIMINACION DE LOS PAQUETES
-- ============================================================

DROP PACKAGE PC_CATEGORIA;
DROP PACKAGE PC_AUTOR;
DROP PACKAGE PC_EDITORIAL;
DROP PACKAGE PC_LIBRO;
DROP PACKAGE PC_EDICION;
DROP PACKAGE PC_EJEMPLAR;
DROP PACKAGE PC_PROVEEDOR;
DROP PACKAGE PC_COMPRA;
DROP PACKAGE PC_USUARIO;
